# Netlify configuration file

[build]
  # Build command: ensure pip exists, upgrade it, install deps, then build
  command = "python -m ensurepip --upgrade && python -m pip install --upgrade pip && python -m pip install -r requirements.txt && python build_site.py"

  # This is the directory that contains the final website files.
  # Since our script generates files in the root, we use "." for the current directory.
  publish = "."

[dev]
  # Command to run the development server
  command = "python build_site.py serve"
  # The port that the development server will run on
  targetPort = 8000
  # The directory to serve files from
  publish = "."
